###
GET http://localhost:3000/users
###
GET http://localhost:3000/users/6494b058a23ae016a0bc3218
###
POST http://localhost:3000/users
content-type: application/json

{
    "name": "John Doe",
    "password": "123456ABC",
    "email": "jonh123@gmail.com",
    "phone_number": "1234556789",
    "createdAt": "2023-06-23T10:49:24.000Z",
    "updatedAt": "2023-06-23T10:49:24.000Z",
    "thumbnail": "1.png"
}

###
GET http://localhost:3000/events
###
GET http://localhost:3000/events/6494b076a23ae016a0bc321b
###
GET http://localhost:3000/events/createdBy/6487c6cdfac6d6f908771e7f
###
POST http://localhost:3000/events
content-type: application/json

{
    "name": "Church Basketball",
    "local": "Church",
    "createdBy": "6487c6cdfac6d6f908771e7f",
    "createdAt": "2023-06-23T10:49:24.000Z",
    "updatedAt": "2023-06-23T10:49:24.000Z"
}
###
PUT http://localhost:3000/users/6494b058a23ae016a0bc3218
Content-Type: application/json

{
  "name": "Jane Doe",
  "password": "newPassword123",
  "email": "Janedoe@example.com",
  "phone_number": "1234567890"
}

###
PUT http://localhost:3000/events/64b2ea81b84a9b37f4358cfe
Content-Type: application/json

{
  "name": "Updated Event Name",
  "local": "Updated Event Location"
}

### 
DELETE http://localhost:3000/events/64b06f315ef8358a663b1381

###
DELETE http://localhost:3000/users/64b1a222829bc319d153fa84


###
POST http://localhost:3000/addresses
content-type: application/json

{
    "address": "This is a dummy address",
    "createdAt": "2023-06-23T10:49:24.000Z",
    "updatedAt": "2023-06-23T10:49:24.000Z"
}
###
GET http://localhost:3000/addresses
### 
DELETE http://localhost:3000/addresses/64b59ebaf13176d6f28acbd5
###
GET http://localhost:3000/activities
###
POST http://localhost:3000/activities
content-type: application/json

{
    "name": "Basketball",
    "min": "10",
    "max": "30"
}
### 
DELETE http://localhost:3000/activities/64b5b1d5a0a37e9a14c88007