###
GET http://localhost:3000/users
###
GET http://localhost:3000/users/6494b058a23ae016a0bc3218
###
POST http://localhost:3000/users
content-type: application/json

{
    "name": "John Doe",
    "password": "123456ABC",
    "email": "jonh123@gmail.com",
    "phone_number": "1234556789",
    "createdAt": "2023-06-23T10:49:24.000Z",
    "updatedAt": "2023-06-23T10:49:24.000Z",
    "thumbnail": "1.png"
}

###
GET http://localhost:3000/events
###
GET http://localhost:3000/events/6494b076a23ae016a0bc321b
###
GET http://localhost:3000/events/createdBy/6487c6cdfac6d6f908771e7f
###
POST http://localhost:3000/events
content-type: application/json

{
    "name": "Church Basketball",
    "local": "Church",
    "createdBy": "6487c6cdfac6d6f908771e7f",
    "createdAt": "2023-06-23T10:49:24.000Z",
    "updatedAt": "2023-06-23T10:49:24.000Z"
}
###
PUT http://localhost:3000/users/6494b058a23ae016a0bc3218
Content-Type: application/json

{
  "name": "Jane Doe",
  "password": "newPassword123",
  "email": "Janedoe@example.com",
  "phone_number": "1234567890"
}

###
PUT http://localhost:3000/events/649ca609400c0310bf800bd3
Content-Type: application/json

{
  "name": "Updated Event Name",
  "local": "Updated Event Location"
}

### 
DELETE http://localhost:3000/events/6494b076a23ae016a0bc321b

###
DELETE http://localhost:3000/users/6494b058a23ae016a0bc3218
